name: Run Pytest

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: "postgres"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: PYTHONPATH=src pytest

      - name: Failure Log
        if: failure()
        run: echo "一つ前のstepは失敗しました"

      - name: Print DB_USER
        run: echo "DB_USER -> ${DB_USER}"

      - name: Print secrets
        run: echo "NAINGNAING_API_KEY -> ${{ secrets.NAINGNAING_API_KEY}}"
